apiVersion: apps/v1
kind: Deployment
metadata:
  name: worlddeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: world
  template:
    metadata:
      labels:
        app: world
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: world-service
        image: sunilvurandur1/world_service:latest
        ports:
        - containerPort: 3000
