apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellodeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      imagePullSecrets:
      - name: my-registry-key
      containers:
      - name: hello-service
        image: sunilvurandur1/hello_service:latest
        ports:
        - containerPort: 8000
